### ISSUE TITLE
Colab example error and predict_structure_no_templates function return empty structure

### ISSUE THREAD

**Issue by Douglas2Code** [delalamo/af2_conformations#10]
Hi, thanks for sharing this wonderful work. I am trying to use colab to run the choose_templates.ipynb file with the sample inputs you provide, it returns with the following error:

INFO:absl:seq	pdb	cid	evalue
INFO:absl:101	4PK0_A	0.987	5.435E-53
INFO:absl:Launching subprocess "hhsearch -i /tmp/tmpmztdeu7h/query.a3m -o /tmp/tmpmztdeu7h/output.hhr -maxseq 1000000 -d T4_lysozyme_bdd05_env/templates_101/pdb70"
INFO:absl:Started HHsearch query
INFO:absl:Finished HHsearch query in 0.002 seconds
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-5-8f234999d714>](https://localhost:8080/#) in <module>()
     42         max_msa_clusters = nseq // 2,
     43         max_extra_msa = nseq,
---> 44         max_recycles = 1
     45     )
     46 

2 frames
[/content/alphafold/data/tools/hhsearch.py](https://localhost:8080/#) in query(self, a3m)
     94         raise RuntimeError(
     95             'HHSearch failed:\nstdout:\n%s\n\nstderr:\n%s\n' % (
---> 96                 stdout.decode('utf-8'), stderr[:100_000].decode('utf-8')))
     97 
     98       with open(hhr_path) as f:

RuntimeError: HHSearch failed:
stdout:

stderr:
- 16:00:50.930 ERROR: In /opt/conda/conda-bld/hhsuite_1616660820288/work/src/ffindexdatabase.cpp:16: FFindexDatabase:

- 16:00:50.930 ERROR: 	could not open file 'T4_lysozyme_bdd05_env/templates_101/pdb70_cs219.ffindex'

It is weird since I remember I was able to run it around two weeks ago.

**Comment by davidesala** [comment]
I'm experiencing the same issues. I also noticed that people are starting to complain for the same error on the  HHsuite github page https://github.com/soedinglab/hh-suite/issues 
Probably they have changed something of the API

**Comment by davidesala** [comment]
bug fixed as reported in an other issue.
