### ISSUE TITLE
Unexpected keyword argument 'param_axis'

### ISSUE THREAD

**Issue by Nicolas-Ball** [delalamo/af2_conformations#16]
I ran into this error trying to run the pre-loaded example choose_templates.ipynb notebook. I was wondering if anyone else has encountered this issue, thanks in advance.

UnfilteredStackTrace                      Traceback (most recent call last)
[<ipython-input-3-d99b6f8e46a2>](https://localhost:8080/#) in <module>
     36     # Run the job and save as a PDB
---> 37     predict.predict_structure_from_templates(
     38         mmseqs2_runner.seq, # NOTE mmseqs2_runner removes whitespace from seq

66 frames
UnfilteredStackTrace: TypeError: __init__() got an unexpected keyword argument 'param_axis'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
[/content/alphafold/model/common_modules.py](https://localhost:8080/#) in __init__(self, axis, create_scale, create_offset, eps, scale_init, offset_init, use_fast_variance, name, param_axis)
    148                name=None,
    149                param_axis=None):
--> 150     super().__init__(
    151         axis=axis,
    152         create_scale=False,

TypeError: __init__() got an unexpected keyword argument 'param_axis'

**Comment by gandrianov** [comment]
Installation of fresh version of dm-haiku (e.g 0.0.9 instead of 0.0.5) helped me to solve this problem

**Comment by delalamo** [comment]
Thanks for bringing to my attention. Both jupyter notebooks now install using the alphafold requirements file, instead of hardcoded module versions. This will hopefully prevent the problem from popping up in the future.
