### ISSUE TITLE
Error in util.py

### ISSUE THREAD

**Issue by rgumpper** [delalamo/af2_conformations#2]
/content/af2_conformations/scripts/util.py in <module>()
    122 def mutate_msa(
    123     a3m_lines: str,
--> 124     pos_res: Dict[ int, str ],
    125   ) -> str:
    126   r""" Mutates every position in an MSA to a residue of interest

NameError: name 'Dict' is not defined

Getting following error after initiating...looks like Dict should be dict

**Comment by delalamo** [comment]
Can you try now? I added a new commit and defined Dict from the typing library

**Comment by delalamo** [comment]
I ran a test that suggests to me that the issue has been addressed. Please feel free to reopen the issue if it persists.
