### ISSUE TITLE
Could not find HHsearch database /pdb70

### ISSUE THREAD

**Issue by imdanique** [delalamo/af2_conformations#7]
Hello!
I git cloned the source codes of af2_conformations and alphafold, and tried to run the script with templates:

```python
#!/bin/python

from af2_conformations.scripts import mmseqs2, predict

# Jobname for reference
jobname = 'CCR3'

# Amino acid sequence. Whitespace and inappropriate characters are automatically removed
sequence = "METPNTTEDYDTTTEFDYGDATPCQKVNERAFGAQLLPPLYSLVFVIGLVGNILVVLVLVQYKRLKNMTSIYLLNLAISDLLFLFTLPFWIDYKLKDDWVFGDAMCKILSGFYYTGLYSEIFFIILLTIDRYLAIVHAVFALRARTVTFGVITSIIIWALAILASMPGLYFSKTQWEFTHHTCSLHFPHESLREWKLFQALKLNLFGLVLPLLVMIICYTGIIKILLRRPNEKKSKAVRLIFVIMIIFFLFWTPYNLTILISVFQDFLFTHECEQSRHLDLAVQVTEVIAYTHCCVNPVIYAFVGERFRKYLRQLFHRRVAVHLVKWLPFLSVDRLERVSSTSPSTGEHELSAGF"

# PDB IDs, written uppercase with chain ID specified 
pdbs = ["7VLA_E",
        "7VL9_E",
        "7O7F_C",
        "7F1R_A"]

# Initializes the Runner object that queries the MMSeqs2 server
mmseqs2_runner = mmseqs2.MMSeqs2Runner( jobname, sequence )

# Fetches the data and saves to the appropriate directory
a3m_lines, template_path = mmseqs2_runner.run_job( templates = pdbs )

# Use templates
predict.predict_structure_from_templates( sequence, "ccr3_out.pdb",
        a3m_lines, template_path = template_path,
        model_id = 1, max_msa_clusters = 16, max_extra_msa = 32,
        max_recycles = 1, n_struct_module_repeats = 8 )
```

However, then I encountered this kind of error:

```bash
prom@PCT0223:/data/af$ python ccr3.py 
WARNING:absl:No templates found.
ERROR:absl:Could not find HHsearch database /pdb70
Traceback (most recent call last):
  File "ccr3.py", line 27, in <module>
    max_recycles = 1, n_struct_module_repeats = 8 )
  File "/data/af/af2_conformations/scripts/predict.py", line 199, in predict_structure_from_templates
    seq, a3m_lines, util.mk_template(seq, a3m_lines, template_path).features
  File "/data/af/af2_conformations/scripts/util.py", line 69, in mk_template
    binary_path="hhsearch", databases=[f"{ path }/pdb70"]
  File "/data/af/alphafold/data/tools/hhsearch.py", line 57, in __init__
    raise ValueError(f'Could not find HHsearch database {database_path}')
ValueError: Could not find HHsearch database /pdb70
```
What does it mean? I didn't download pdb70 database locally, but it seems that I don't have to.

**Comment by delalamo** [comment]
Thanks for reporting this. You are correct, that you are not downloading the full PDB70. Instead, that is the name assigned to the mini-DB that is retrieved by the MMSeqs2 server when you request templates. In this case as you can see no templates were retrieved. This may be because A) the server has not been updated to include these structures, which I can see are all quite new, or B) the structures are not the first of the proteins of interest to have been determined and may have been trimmed during curation of the full PDB70 that is searched by the MMSeqs2 server.

Unfortunately I don't have a fix for this at the moment. Two possible ways forward are to either use the ColabFold custom templates notebook, or to run AF2 locally using a manually curated DB.

Sorry I couldn't be of more help!

Diego

**Comment by imdanique** [comment]
@delalamo Thank you for the quick answer! Is there any way to use full PDBs locally instead of retrieving structures from pdb70? If it's not possible using your notebook, can you suggest another way how to do this?

**Comment by delalamo** [comment]
I am not aware of a way to do this over the MMSeqs2 server. I should mention, you can build a custom DB with whichever structures you want,. including the entire PDB, on your local workstation and then upload it to colab. Then you just assign the directory to the variable `template_paths`. To do this, simply follow the instructions [here](https://github.com/soedinglab/hh-suite/wiki#building-customized-databases). Note that you need a local installation of [hh-suite](https://github.com/soedinglab/hh-suite). I have gotten this to work without doing the secondary structure prediction step that is flagged as "optional".
