### ISSUE TITLE
HHSearch failed

### ISSUE THREAD

**Issue by ClaireLiseMadjarian** [delalamo/af2_conformations#9]
Hello ! I've recently encountered a problem with the choose_templates notebook. I tried to run it with specific templates and got the following error  : 

[/content/alphafold/data/tools/hhsearch.py](https://localhost:8080/#) in query(self, a3m)
     94         raise RuntimeError(
     95             'HHSearch failed:\nstdout:\n%s\n\nstderr:\n%s\n' % (
---> 96                 stdout.decode('utf-8'), stderr[:100_000].decode('utf-8')))
     97 
     98       with open(hhr_path) as f:

RuntimeError: HHSearch failed:
stdout:
stderr:
- 15:01:16.302 ERROR: In /opt/conda/conda-bld/hhsuite_1645696999782/work/src/ffindexdatabase.cpp:16: FFindexDatabase:
- 15:01:16.302 ERROR: 	could not open file 'test_868ae_env/templates_101/pdb70_cs219.ffindex'

Do you know how I can solve this ? 
Thanks

**Comment by delalamo** [comment]
Are you running locally or in colab?

**Comment by ClaireLiseMadjarian** [comment]
Thank you very much for your reply. I am running in Colab.

**Comment by delalamo** [comment]
Interesting, a quick look suggests that none of the templates you searched for were retrieved, since the ffindex file cannot be found. Can you verify this by looking in the test_868ae_env/templates_101/ folder?

**Comment by ClaireLiseMadjarian** [comment]
I've just installed the PDB70 database from the hh-suite but I cannot 
find any folder named " test_868ae_env/templates_101/ ". Is it the wrong 
database ?

Should I try to create a database containing my templates using the 
hh-suite and then put the folder path in the Google collab ?

**Comment by davidesala** [comment]
I'm experiencing the same issues. I also noticed that people are starting to complain for the same error on the HHsuite github page https://github.com/soedinglab/hh-suite/issues
Probably they have changed something of the API

**Comment by carsten-jahn** [comment]
I believe the API change is backed by a HTTP redirect for compatibility, but we need to tell curl to follow the redirect. In `mmseqs2.py`, `os.system(f"curl -v` needs to be replaced with `os.system(f"curl -vL` to follow the redirect.

**Comment by davidesala** [comment]
> I believe the API change is backed by a HTTP redirect for compatibility, but we need to tell curl to follow the redirect. In `mmseqs2.py`, `os.system(f"curl -v` needs to be replaced with `os.system(f"curl -vL` to follow the redirect.

if only I had seen this before I would have saved my morning. Anyway, we fixed the bug by switching to wget. Thanks

**Comment by delalamo** [comment]
Interesting, a quick look suggests that none of the templates you searched
for were retrieved, since the ffindex file cannot be found. Can you verify
this by looking in the test_868ae_env/templates_101/ folder?

**Comment by delalamo** [comment]
No updates and the problem hasn't been reproduced recently.
